"""Kev on two deliberately extreme controls: can it separate stiff report prose from casual writing at all?"""
import json, os, urllib.request
AUTH = {"authorization": "Bearer " + open(os.environ["JEV_KEY_FILE"]).read().strip()}

C = json.load(open("controls.json"))
H = {"type": "noul", "instructions": "Was this paragraph written by a human author rather than generated by an AI language model?"}
S = {"type": "score", "instructions": "How natural does this writing sound, as if a person wrote it by hand?",
     "criteria": ["stiff and machine-like", "somewhat natural", "natural, like a person wrote it"]}
res = {}
for k, v in C.items():
    body = json.dumps({"model": "jev-latest", "state": {"paragraph": v["text"]}, "questions": {"human": H, "natural": S}}).encode()
    req = urllib.request.Request("https://api.typesafe.ai/v1/systemone", data=body, headers={"content-type": "application/json", **AUTH})
    a = json.loads(urllib.request.urlopen(req).read())["answers"]
    p = a["natural"]["probabilities"]
    e = sum(int(i) * float(x) for i, x in p.items()) / 2
    res[k] = {"p_human": a["human"]["noul"], "natural": e}
    print(f"{k:9s} p_human {a['human']['noul']:.3f}  natural {e:.3f}")
json.dump(res, open("jev_controls.json", "w"), indent=1)
