"""Ask a /v1/systemone endpoint which of the ten rewrites sounds most human, three ways, plus two controls.

    python humanness/judge.py --endpoint http://127.0.0.1:8008 --model kev-latest --out humanness/results-kev-4b-4bit.json
    python humanness/judge.py --endpoint https://api.typesafe.ai --model jev-latest --api-key-file ~/.jev_key \
        --out humanness/results-jev.json

For each version: P(human) from a yes/no question, a 3-level naturalness score (expected level scaled 0-1), and its
share when asked to pick the most human of all ten, averaged over ten cyclic rotations of the option order.
"""
import argparse, json, os, urllib.request
from pathlib import Path

HERE = Path(__file__).parent
HUMAN_Q = {"type": "noul", "instructions": "Was this paragraph written by a human author rather than generated by an AI language model?"}
NATURAL_Q = {"type": "score", "instructions": "How natural does this writing sound, as if a person wrote it by hand?",
             "criteria": ["stiff and machine-like", "somewhat natural", "natural, like a person wrote it"]}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--endpoint", required=True); ap.add_argument("--model", default="default")
    ap.add_argument("--api-key-file"); ap.add_argument("--out", required=True)
    a = ap.parse_args()
    key = Path(a.api_key_file).expanduser().read_text().strip() if a.api_key_file else os.environ.get("GUTCHECK_API_KEY") or os.environ.get("JEV_API_KEY", "")
    headers = {"content-type": "application/json"} | ({"authorization": f"Bearer {key}"} if key else {})

    def ask(state, questions):
        body = json.dumps({"model": a.model, "state": state, "questions": questions}).encode()
        req = urllib.request.Request(f"{a.endpoint.rstrip('/')}/v1/systemone", data=body, headers=headers)
        with urllib.request.urlopen(req, timeout=300) as r:
            return json.loads(r.read())["answers"]

    def rate(text):
        ans = ask({"paragraph": text}, {"human": HUMAN_Q, "natural": NATURAL_Q})
        probs = ans["natural"]["probabilities"]
        natural = sum(int(k) * float(v) for k, v in probs.items()) / 2
        return {"p_human": float(ans["human"]["noul"]), "natural": natural}

    versions = json.loads((HERE / "versions.json").read_text())
    controls = json.loads((HERE / "controls.json").read_text())
    out = {"endpoint": a.endpoint, "model": a.model, "versions": {L: rate(v["text"]) for L, v in versions.items()},
           "controls": {c: rate(v["text"]) for c, v in controls.items()}}
    letters = list(versions); pick = dict.fromkeys(letters, 0.0)
    for r in range(len(letters)):
        order = letters[r:] + letters[:r]
        ans = ask({"task": "Ten candidate opening paragraphs for a blog post; each option below is one full paragraph."},
                  {"most_human": {"type": "choice", "instructions": "Which paragraph sounds most like a human wrote it by hand?",
                                  "criteria": {L: versions[L]["text"] for L in order}}})
        for L, p in ans["most_human"]["probabilities"].items():
            pick[L] += float(p) / len(letters)
    for L in letters:
        out["versions"][L]["pick"] = pick[L]
    Path(a.out).write_text(json.dumps(out, indent=1))
    for L in sorted(letters, key=lambda L: -out["versions"][L]["p_human"]):
        v = out["versions"][L]; print(f"{L}  p_human {v['p_human']:.3f}  natural {v['natural']:.3f}  pick {v['pick']:.3f}")
    for c, v in out["controls"].items():
        print(f"{c}  p_human {v['p_human']:.3f}  natural {v['natural']:.3f}")


if __name__ == "__main__":
    main()
