"""Ask Kev (POST /v1/systemone on 127.0.0.1:8008) which of the ten paragraphs sounds most human, three ways."""
import json, sys, urllib.request

KEY = json.load(open(sys.argv[1]))
URL = "http://127.0.0.1:8008/v1/systemone"


def ask(state, questions):
    body = json.dumps({"model": "kev-latest", "state": state, "questions": questions}).encode()
    req = urllib.request.Request(URL, data=body, headers={"content-type": "application/json"})
    with urllib.request.urlopen(req, timeout=300) as r:
        return json.loads(r.read())["answers"]


HUMAN_Q = {"type": "noul", "instructions": "Was this paragraph written by a human author rather than generated by an AI language model?"}
SCORE_Q = {"type": "score", "instructions": "How natural does this writing sound, as if a person wrote it by hand?",
           "criteria": ["stiff and machine-like", "somewhat natural", "natural, like a person wrote it"]}

out = {}
for L, v in KEY.items():
    a = ask({"paragraph": v["text"]}, {"human": HUMAN_Q, "natural": SCORE_Q})
    probs = a["natural"].get("probabilities") or {}
    vals = [float(probs[k]) for k in sorted(probs, key=lambda k: int(k))] if probs else []
    expected = sum(i * p for i, p in enumerate(vals)) / 2 if vals else None   # 0..1
    out[L] = {"p_human": a["human"]["noul"], "natural": expected}

# pick-one over all ten, averaged over 10 cyclic rotations of the option order
letters = list(KEY)
pick = {L: 0.0 for L in letters}
for r in range(len(letters)):
    order = letters[r:] + letters[:r]
    crit = {L: KEY[L]["text"] for L in order}
    a = ask({"task": "Ten candidate opening paragraphs for a blog post; each option below is one full paragraph."},
            {"most_human": {"type": "choice", "instructions": "Which paragraph sounds most like a human wrote it by hand?", "criteria": crit}})
    for L, p in a["most_human"]["probabilities"].items():
        pick[L] += float(p) / len(letters)
for L in letters:
    out[L]["pick"] = pick[L]

json.dump(out, open(sys.argv[2], "w"), indent=1)
print("L  p_human  natural  pick-one")
for L in sorted(out, key=lambda L: -out[L]["p_human"]):
    o = out[L]
    print(f"{L}  {o['p_human']:.3f}    {o['natural']:.3f}    {o['pick']:.3f}")
